// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAGestionale.Models;

public partial class BuyRequest
{
    public long ID { get; set; }

    public long IDproduct { get; set; }

    public long IDbuyer { get; set; }

    public DateTime Date { get; set; }
}