// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MAGestionaleV2.Models;

public partial class Product
{
    public long ID { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string ImagePath { get; set; }

    public decimal Price { get; set; }

    public long IDSeller { get; set; }

    public bool IsVisible { get; set; }
}